### ISSUE TITLE
 The cluster cannot be created with basic authentication enabled

### ISSUE THREAD

**Issue by rmarquesa** [orlandothoeny/terraform-gcp-gke-infrastructure#1]
Thanks for share your solution, but I need a help with the error:

Error: googleapi: Error 400: Basic authentication was removed for GKE cluster versions >= 1.19. The cluster cannot be created with basic authentication enabled. Instructions for choosing an alternative authentication method can be found at: https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication., badRequest
│
│   with module.google_kubernetes_cluster.google_container_cluster.app_cluster,
│   on modules\kubernetes_cluster\main.tf line 1, in resource "google_container_cluster" "app_cluster":
│    1: resource "google_container_cluster" "app_cluster" {

**Comment by orlandothoeny** [comment]
You can just remove the username & password from https://github.com/orlandothoeny/terraform-gcp-gke-infrastructure/blob/main/infrastructure/kubernetes_cluster/main.tf#L27-L28

**Comment by rmarquesa** [comment]
Thank you Orlando, very nice!
